### ISSUE TITLE
General CSS issues

### ISSUE THREAD

**Issue by jbjorge** [adeptoas/sweet-modal-vue#2]
Hi,
I tried using your library, but it needs a lot of manual css-overrides to make it work like I want it to.
It currently:

- Uses the Roboto-font instead of whatever is defined on e.g. `<body>`
- Pollutes/gets polluted by other css-frameworks
    - e.g. `.title` is very general and should be named `.sweet-modal-title`
- Disallows long titles in `sweet-modal-tab`

**Comment by bluefirex** [comment]
Yeah, this makes sense. I tried to keep the classes short but apparently this causes some problems. I'll review this and update you on it.

For the third point: This is actually a bug. Can you open a separate issue for that?

**Comment by bluefirex** [comment]
1. Fixed in e6a56d6c0729a0f37570ba6c775ea43a04e1f25b.
2. Fixed in 4a0bbe2312653d8fb2859d572be7564b1e15bf2d and 122fffa7e3e264b3ecf16b5ba75e3e8d03fb10ff
3. Fixed in d98884fa1345cb63524f9056976f2b596b0cb78e

Everything released in [v1.1.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.0)
