### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by packytagliaferro** [adeptoas/sweet-modal-vue#21]
I added this to a new Laravel project that I use vue in and get this error:

```
error  in ./~/sweet-modal-vue/src/components/SweetModal.vue

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/PackyTagliaferro/Site
s/league/node_modules/sweet-modal-vue"
```

**Comment by packytagliaferro** [comment]
`npm install babel-preset-es2015 --save
`
solved it

**Comment by bluefirex** [comment]
`babel-preset-es2015` is a peer dependency because most projects using Vue are also using ES6 so it uses your locally installed version of it instead of installing its own one.

**Comment by nkoterba** [comment]
@bluefirex I think part of the issue is you include the `.babelrc` file in your NPM distribution.  Thus, when loaders in webpack try to load the Vue component, it tries to reference the local `.babelrc` file included which then demands the babel `es2015` preset.

I've looked at a few other libraries and they do not seem to include the `.babelrc` file especially if they actually already *babel-ize* to create their `dist` files.

If your "dist" is already transpiled to safe es5 syntax, then there's no need to include this `.babelrc` file and users of your library can choose their own version of babel and its presets.

I haven't had to deal with this issue myself as a library maintainer and what the best practices are but from what I see no other 3rd party component libs include the `.bablerc` file in their NPM distro.

**Comment by nkoterba** [comment]
As a brief followup, latest versions of babel are also throwing a deprecation warnings since babel now suggests using babel-preset-env instead of `es2015`:

```javascript
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
```

**Comment by bluefirex** [comment]
Thanks for your feedback. I'll look into this.
Regarding the deprecation warning, I'm aware of it. The next version will of course siwtch to env.

**Comment by smpl** [comment]
i have same problem
step to reproduce
```
vue-cli webpack
npm install sweet-modal-vue --save-dev
npm install babel-preset-es2015 --save
```
add import { SweetModal, SweetModalTab } from 'sweet-modal-vue'
and i have problem with es2015
